# Generated by Django 6.1.1 on 2026-09-28 05:18

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=150)),
                ('message', models.TextField(max_length=3000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(default='Your Name', max_length=100)),
                ('tagline', models.CharField(blank=True, default="Thoughts, stories and things I'm learning.", help_text='Shown on the homepage under the site name.', max_length=200)),
                ('photo', models.ImageField(blank=True, upload_to='profile/')),
                ('about', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='About me')),
                ('contact_intro', models.TextField(blank=True, default='Have a question or just want to say hi? Send me a message.')),
                ('contact_email', models.EmailField(blank=True, help_text='Shown on the Contact page.', max_length=254)),
                ('github_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('x_url', models.URLField(blank=True, verbose_name='X / Twitter URL')),
                ('youtube_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'About & contact details',
                'verbose_name_plural': 'About & contact details',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, help_text="Part of the post's web address. Leave blank to create it from the title.", max_length=220, unique=True)),
                ('summary', models.CharField(blank=True, help_text='One or two sentences shown on the blog list and in search results.', max_length=300)),
                ('cover_image', models.ImageField(blank=True, help_text='Optional. Shown on the post card and at the top of the post.', upload_to='covers/%Y/%m/')),
                ('body', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Body')),
                ('status', models.CharField(choices=[('draft', 'Draft (only you can see it)'), ('published', 'Published')], default='draft', max_length=10)),
                ('published_at', models.DateTimeField(blank=True, help_text='Set automatically when you publish. Choose a future time to schedule a post.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topics', models.ManyToManyField(blank=True, related_name='posts', to='blog.topic')),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
